import React from 'react'
import ReactDOM from 'react-dom/client'
import { useState } from 'react'
import { ArrowDown, ArrowUpRight, Check, ChevronDown, Clock3, MapPin, Menu, Phone, ShieldCheck, Truck, Wrench, X, CarFront, Gauge } from 'lucide-react'
import './styles.css'
const phone = 'tel:+12704436837'
const services = [
  { icon: Wrench, title: 'Mechanical repair', text: 'From engine trouble to electrical diagnostics, let’s get to the source of the problem.', items: 'Engines & transmissions · Exhaust · Suspension' },
  { icon: CarFront, title: 'Collision & body work', text: 'Careful repairs and attention to the details that make your car feel like your car again.', items: 'Collision repair · Painting · Dent repair' },
  { icon: Gauge, title: 'Everyday maintenance', text: 'Keep the small things small with routine care that helps your vehicle go the distance.', items: 'Oil changes · Brakes · Alignments' },
  { icon: Truck, title: 'Towing & roadside help', text: 'A tough day on the road? Call us for help getting you and your vehicle moving again.', items: '24/7 towing · Lockouts · Fuel delivery' },
]
const faqs = [
  ['Can I get an estimate?', 'Yes. We offer free estimates. Bring your vehicle in so our team can inspect it and explain the recommended repairs and costs. Call ahead to arrange a visit.'],
  ['What kinds of repairs do you handle?', 'We offer mechanical repairs, routine maintenance, collision and auto body repair, painting, and detailing. Give us a call to discuss your vehicle and the work it needs.'],
  ['Do you offer towing after hours?', 'Yes, towing is available 24 hours a day, seven days a week. Call (270) 443-6837 for assistance.'],
  ['Where is the shop?', 'You’ll find us at 818 South 3rd Street in Paducah, Kentucky. We also serve drivers from Benton, Mayfield, Murray, and the surrounding communities.'],
]
function App() {
  const [menuOpen, setMenuOpen] = useState(false)
  return <>
    <a className="skip-link" href="#main">Skip to content</a>
    <div className="topbar"><span><MapPin size={13} /> Proudly serving Paducah, KY since 1968</span><a href={phone}>Need a tow? We’re here 24/7 <ArrowUpRight size={13} /></a></div>
    <header className="header"><a className="brand" href="#" aria-label="BA’s Automotive Service home"><img className="brand-logo" src="/ba-automotive-logo.png" alt="BA’s Automotive Service Inc." width="375" height="375" /></a><button className="menu-toggle" aria-label={menuOpen ? 'Close navigation' : 'Open navigation'} aria-expanded={menuOpen} aria-controls="navigation" onClick={() => setMenuOpen(!menuOpen)}>{menuOpen ? <X /> : <Menu />}</button><nav id="navigation" className={menuOpen ? 'nav open' : 'nav'} aria-label="Main navigation">{['Services', 'About us', 'FAQs', 'Contact'].map((name, i) => <a key={name} onClick={() => setMenuOpen(false)} href={`#${['services', 'about', 'faqs', 'contact'][i]}`}>{name}</a>)}</nav><a className="header-call" href={phone} aria-label="Call (270) 443-6837"><Phone size={16} /><span>(270) 443-6837</span></a></header>
    <main id="main"><section className="hero"><div className="hero-copy"><div className="eyebrow"><span /> YOUR NEIGHBORHOOD AUTO SHOP</div><h1>Good people.<br />Honest work.<br /><em>Back on the road.</em></h1><p>From the everyday tune-up to the unexpected repair, we’re here to take care of your car—and the person behind the wheel.</p><div className="hero-actions"><a className="button primary" href={phone}>Let’s talk about your car <ArrowUpRight size={19} /></a><a className="text-link" href="#services">Explore our services <ArrowDown size={16} /></a></div><div className="hero-assurance"><ShieldCheck size={18} /><span>Locally rooted. Keeping Paducah moving since 1968.</span></div></div>
      <div className="hero-art" role="img" aria-label="Illustration of a classic car inside an automotive service garage"><div className="garage-grid" /><div className="garage-label">BA’S / SERVICE BAY 01</div><div className="garage-light" /><div className="garage-number">68</div><svg className="car" viewBox="0 0 700 420" aria-hidden="true"><defs><linearGradient id="body" x2="0.2" y2="1"><stop stopColor="#e9a1a3" /><stop offset=".45" stopColor="#b32c32" /><stop offset="1" stopColor="#681c22" /></linearGradient><linearGradient id="glass" x2="1" y2="1"><stop stopColor="#b7bcc2" /><stop offset="1" stopColor="#30343b" /></linearGradient></defs><ellipse cx="350" cy="350" rx="298" ry="29" fill="#101012" opacity=".7" /><path d="M90 235L158 211 224 130Q242 109 276 108H416Q449 108 470 133L532 213 617 239Q641 248 640 282L634 315H66L62 277Q62 247 90 235Z" fill="url(#body)" stroke="#551b21" strokeWidth="3" /><path d="M189 208L244 140Q252 131 279 131H329V208Z" fill="url(#glass)" stroke="#e7a0a3" strokeWidth="7" /><path d="M350 131H407Q427 131 439 148L486 208H350Z" fill="url(#glass)" stroke="#e7a0a3" strokeWidth="7" /><path d="M333 223V302M507 225V300M87 245H611" fill="none" stroke="#7d2229" strokeWidth="3" /><path d="M77 307H634" stroke="#d9dadd" strokeWidth="12" /><path d="M373 230H401" stroke="#e4e4e7" strokeWidth="6" strokeLinecap="round" /><rect x="70" y="259" width="39" height="18" rx="4" fill="#f4e8b7" /><rect x="603" y="254" width="28" height="21" rx="3" fill="#a42722" />{[179, 529].map(x => <g key={x}><circle cx={x} cy="308" r="57" fill="#161618" /><circle cx={x} cy="308" r="35" fill="#b0b3b8" /><circle cx={x} cy="308" r="23" fill="#484c52" /><circle cx={x} cy="308" r="10" fill="#d0d2d6" />{[0, 60, 120].map(r => <path key={r} d={`M${x - 29} 308h58`} transform={`rotate(${r} ${x} 308)`} stroke="#c7c9ce" strokeWidth="5" />)}</g>)}<path d="M238 143L211 192M368 141L412 199" stroke="#e0e5ec" opacity=".25" strokeWidth="10" /></svg><div className="art-caption"><span>BUILT ON TRUST.<br /><strong>Driven by our community.</strong></span><span className="round-arrow"><ArrowUpRight /></span></div><div className="est-stamp">EST.<strong>1968</strong>PADUCAH, KY</div></div></section>
      <div className="trust-strip"><span><Check /> Free repair estimates</span><span><ShieldCheck /> ASE-certified technicians</span><span><Wrench /> Full-service auto care</span><span><Truck /> 24/7 towing available</span></div>
      <section id="services" className="section"><div className="section-heading"><div><div className="eyebrow">WHAT WE DO</div><h2>One shop. A whole lot of know-how.</h2></div><p>Whatever brings you in, we’ll help you<br /> find the right way forward.</p></div><div className="service-grid">{services.map(({ icon: Icon, title, text, items }, i) => <article className="service-card" key={title}><div className="card-top"><Icon size={29} strokeWidth={1.5} /><span>0{i + 1}</span></div><h3>{title}</h3><p>{text}</p><div className="service-items">{items}</div><a href={phone} aria-label={`Call about ${title.toLowerCase()}`}>Talk to our team <ArrowUpRight size={17} /></a></article>)}</div></section>
      <section id="about" className="about section"><div className="heritage"><span className="eyebrow">A PADUCAH ORIGINAL</span><div className="heritage-year">Since<br /><strong>1968.</strong></div><span className="heritage-bottom">LOCAL ROOTS. LASTING RELATIONSHIPS.</span></div><div className="about-copy"><div className="eyebrow">MORE THAN A REPAIR SHOP</div><h2>Your car matters.<br />So does your peace of mind.</h2><p>We’ve been part of the Paducah community for over five decades. At BA’s, we believe taking care of a vehicle starts with taking care of its owner.</p><p>Whether you need a little maintenance or a major repair, our team brings experience, careful workmanship, and a friendly face to the job.</p><a className="text-link" href="#contact">Come by. Let’s get acquainted. <ArrowUpRight size={19} /></a></div></section>
      <section className="section faq-section" id="faqs"><div><div className="eyebrow">A LITTLE CLARITY</div><h2>Before you<br />hand us the keys.</h2><p>Have something else on your mind?<br /><a href={phone}>Give us a call. We’re happy to help.</a></p></div><div className="faq-list">{faqs.map(([question, answer]) => <details key={question}><summary>{question}<ChevronDown size={19} /></summary><p>{answer}</p></details>)}</div></section>
      <section className="contact section" id="contact"><div><div className="eyebrow">LET’S GET YOU MOVING</div><h2>Good service<br />starts with a hello.</h2><a className="contact-phone" href={phone}>(270) 443-6837 <ArrowUpRight /></a><a className="email" href="mailto:bassvc@bellsouth.net">bassvc@bellsouth.net</a></div><div className="contact-details"><div><MapPin /><h3>Find the shop</h3><p>818 South 3rd Street<br />Paducah, KY 42003</p><a href="https://www.google.com/maps/search/?api=1&query=818+South+3rd+St+Paducah+KY+42003" target="_blank" rel="noreferrer">Get directions <ArrowUpRight size={16} /></a></div><div><Clock3 /><h3>Shop hours</h3><p>Monday–Friday<br />8:00 AM–5:00 PM</p><small>Holiday hours may vary. Please call.<br />24/7 towing available.</small></div></div></section></main>
    <footer><a className="brand" href="#"><img className="brand-logo" src="/ba-automotive-logo.png" alt="BA’s Automotive Service Inc." width="375" height="375" /></a><p>© {new Date().getFullYear()} BA’s Automotive Service Inc.</p><a href="#main">Back to top ↑</a></footer>
  </>
}
ReactDOM.createRoot(document.getElementById('root')!).render(<React.StrictMode><App /></React.StrictMode>)
